# Exercise 3: Numpy

Perform the follwing tasks:


In [50]:
#3.1: import the num#import an read big-mart data
import numpy as np
from numpy.linalg import inv

In [71]:
#3.2: create a random 10x10 array named A
#array = np.arange(100).reshape(10,10)
#array = np.zeros((10,10))
array = np.random.rand(10,10)
array


array([[0.0708435 , 0.50125674, 0.3972867 , 0.35925044, 0.98553286,
        0.59087623, 0.94640237, 0.0693969 , 0.62616303, 0.36696692],
       [0.8853863 , 0.75173718, 0.34662945, 0.53696203, 0.27525908,
        0.85913981, 0.89522795, 0.30139279, 0.80683182, 0.94729728],
       [0.31528735, 0.96160577, 0.45302641, 0.09370467, 0.5277271 ,
        0.40287482, 0.88762781, 0.44788169, 0.84466408, 0.2155683 ],
       [0.25841038, 0.57820145, 0.04093482, 0.68974712, 0.06660288,
        0.12419275, 0.39573388, 0.09452887, 0.73990336, 0.99487847],
       [0.93557952, 0.09836081, 0.27131647, 0.06270306, 0.0474891 ,
        0.02791821, 0.28394747, 0.46426913, 0.66233085, 0.04995713],
       [0.87722284, 0.55595428, 0.33336397, 0.02854737, 0.48626189,
        0.39832819, 0.2012287 , 0.59366236, 0.87198254, 0.72675071],
       [0.69812927, 0.62260599, 0.06636779, 0.45785074, 0.02813745,
        0.22615703, 0.39164474, 0.97242984, 0.32672997, 0.52388162],
       [0.49412666, 0.58984076, 0.7822125

In [72]:
#3.3: return only the odd rows of A
array[::2]

array([[0.0708435 , 0.50125674, 0.3972867 , 0.35925044, 0.98553286,
        0.59087623, 0.94640237, 0.0693969 , 0.62616303, 0.36696692],
       [0.31528735, 0.96160577, 0.45302641, 0.09370467, 0.5277271 ,
        0.40287482, 0.88762781, 0.44788169, 0.84466408, 0.2155683 ],
       [0.93557952, 0.09836081, 0.27131647, 0.06270306, 0.0474891 ,
        0.02791821, 0.28394747, 0.46426913, 0.66233085, 0.04995713],
       [0.69812927, 0.62260599, 0.06636779, 0.45785074, 0.02813745,
        0.22615703, 0.39164474, 0.97242984, 0.32672997, 0.52388162],
       [0.70883189, 0.33757348, 0.26537296, 0.45786826, 0.07331777,
        0.48287051, 0.44310148, 0.66591214, 0.81552377, 0.04627688]])

In [73]:
#3.4: perform a matrix multiplication of A with it's transposed
# Easiest done with np dot, .T  (no other variable needed here!)

#testArray = array.transpose(1,0)
#array.T
transposedMatrix = np.dot(array, array.T)
transposedMatrix

array([[3.29082268, 3.27007106, 2.9552723 , 1.92068187, 1.04320564,
        2.24244616, 1.54872526, 2.13336024, 1.84011685, 3.14314519],
       [3.27007106, 5.01200706, 3.51608817, 3.09522334, 2.04290259,
        3.55262615, 2.96063167, 3.13674232, 2.95344162, 3.61703016],
       [2.9552723 , 3.51608817, 3.42731748, 2.03887093, 1.58485219,
        2.71967721, 2.16982143, 2.80646645, 2.33483033, 3.21020061],
       [1.92068187, 3.09522334, 2.03887093, 2.60116054, 1.05563808,
        2.16729232, 1.89873155, 2.02751634, 1.65763033, 2.66074191],
       [1.04320564, 2.04290259, 1.58485219, 1.05563808, 1.70291269,
        1.94845052, 1.57401156, 1.86482756, 1.79148347, 1.17332131],
       [2.24244616, 3.55262615, 2.71967721, 2.16729232, 1.94845052,
        3.26711565, 2.41925667, 2.88248857, 2.36825418, 2.71231904],
       [1.54872526, 2.96063167, 2.16982143, 1.89873155, 1.57401156,
        2.41925667, 2.62120321, 2.35758206, 2.15533749, 2.34810868],
       [2.13336024, 3.13674232, 2.8064664

In [78]:
#3.5: compute the matrix inverse of A
#np.linalg.inv(array) 
inverseMatrix = inv(np.matrix(array))
inverseMatrix

matrix([[ 0.84349896, -0.33199789,  0.44649765,  0.56098174,  1.46356675,
          0.2353165 ,  1.17466411, -0.72811697, -1.48695005, -1.14551339],
        [ 0.51295301, -1.05480599,  2.13912397,  1.26455898, -0.03788438,
          0.46063361,  1.56506672, -0.81704376, -1.5688117 , -1.67839435],
        [ 0.87049426,  0.30476495, -0.07410025,  0.02142113,  0.19409109,
         -0.62241883,  0.44080804,  1.37908962, -1.27973961, -1.06987315],
        [ 1.77327074, -1.2108756 ,  0.03070489,  1.58052163,  0.38595544,
         -0.40598724,  1.62856163, -0.30298725, -0.58959593, -1.5672693 ],
        [ 1.70935671, -1.30456437,  0.00354562,  0.48064554,  0.42917132,
          0.84838537,  0.99673513, -0.58602647, -0.87697251, -0.74358261],
        [-0.55719941,  1.015996  , -0.40010753, -0.97278571, -1.57352611,
          0.52129936, -0.7498377 , -0.01463191,  1.4854346 ,  0.34508116],
        [-0.75447876,  1.30282848, -0.39744953, -1.04222394,  0.64609237,
         -1.35575243, -0.8685180

In [83]:
#3.6: divide all entries of A which are lager than 0.5 by 2 (hint: use where() )
#Divided by 20 so that it is more obvious

In [85]:
np.where(array < 0.5, array, array / 20)

array([[0.0708435 , 0.02506284, 0.3972867 , 0.35925044, 0.04927664,
        0.02954381, 0.04732012, 0.0693969 , 0.03130815, 0.36696692],
       [0.04426931, 0.03758686, 0.34662945, 0.0268481 , 0.27525908,
        0.04295699, 0.0447614 , 0.30139279, 0.04034159, 0.04736486],
       [0.31528735, 0.04808029, 0.45302641, 0.09370467, 0.02638636,
        0.40287482, 0.04438139, 0.44788169, 0.0422332 , 0.2155683 ],
       [0.25841038, 0.02891007, 0.04093482, 0.03448736, 0.06660288,
        0.12419275, 0.39573388, 0.09452887, 0.03699517, 0.04974392],
       [0.04677898, 0.09836081, 0.27131647, 0.06270306, 0.0474891 ,
        0.02791821, 0.28394747, 0.46426913, 0.03311654, 0.04995713],
       [0.04386114, 0.02779771, 0.33336397, 0.02854737, 0.48626189,
        0.39832819, 0.2012287 , 0.02968312, 0.04359913, 0.03633754],
       [0.03490646, 0.0311303 , 0.06636779, 0.45785074, 0.02813745,
        0.22615703, 0.39164474, 0.04862149, 0.32672997, 0.02619408],
       [0.49412666, 0.02949204, 0.0391106